[[DeviceList]]
  Name = "GasSensor"
  ProfileName = "BME680"
  # Description = "Gas sensor"
  # Labels = [ "industrial" ]
  [DeviceList.Protocols]
  [DeviceList.Protocols.i2c]
    Address = "0x76"
  [[DeviceList.AutoEvents]]
    Interval = "30s"
    OnChange = false
    SourceName = "ReadAll"
  # [[DeviceList.AutoEvents]]
  #   Interval = "30s"
  #   OnChange = false
  #   SourceName = "Image"
